### ISSUE TITLE
Banners sometimes do not render to other players until relog

### ISSUE THREAD

**Issue by NightFuryStrike** [egg82/AdvancedEnchantments#23] opened 2019-11-13 01:24 UTC
Plugin version: '4.18.24'
Server type: 'Paper Build #225'
Server version: '1.14.4'

**Describe the bug**
Here's another strange bug me and my players found:
Sometimes, when another player places a banner, it has a chance that it will not render to other players until they relog. It renders fine for the player who placed it though.

**Expected behavior**
Banners should always render to all players.

**To Reproduce**
1. Install the plugin (with ProtocolLib, I did not test without ProtocolLib)
2. Start server and join with two accounts (or contact me and I can show you on my server if you like)
3. Create some random custom banners, and place them on the ground with one account
4. Observe the other account, the result should be the other account not being able to see all banners that were placed.

**Plugins**
Advanced Enchantments, ProtocolLib

**Screenshots/Video**
https://1drv.ms/v/s!AknzfCjeCluIoe1uPNuLFdxHKThltA?e=m5oHfB

**Additional context**
I assume it's another issue with ProtocolLib.

**Comment by NightFuryStrike** [comment] 2019-11-14 06:47
Update:
My players have noticed this issue affects skulls as well, can be seen happening in this video:
https://1drv.ms/v/s!AknzfCjeCluIoe4EIovTWj_u-KoiQA?e=nMZdOf

**Comment by egg82** [comment] 2019-11-14 16:25
Might have something to do with the new fake block handling, but that might be related more to PLib than to AE. Packets are a nightmare.

**Comment by egg82** [comment] 2019-11-14 16:35
Re-opening in case the issue is still present. Will lose once confirmed fixed.

**Comment by egg82** [comment] 2019-11-22 01:50
Assuming this is fixed now. Re-open if not.

**Closed by egg82** 2019-11-22 01:50 UTC
Labels: bug
